name: Build and deploy Node.js app to Azure

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
      
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        
    - name: 'Resolve Project Dependencies Using Npm'
      run: |
        npm install
        npm run build --if-present

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ids-frontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
